name       : rubyzip
version    : 2.3.0
release    : 5
source     :
    - https://rubygems.org/downloads/rubyzip-2.3.0.gem : 5196155ab0d4060e4b4a482c1c1bd43198149605bd925fee4d40c494afa82015
license    : BSD-2-Clause
component  : programming.ruby
summary    : RubyGem - rubyzip
description: |
    rubyzip is a ruby module for reading and writing zip files.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
